{ pkgs, ... }:

{
  # System packages
  environment.systemPackages = with pkgs; [
    audacity
    #appimage-run
    btop
    #distrobox
    #dolphin-emu
    #duckstation
    eza
    fastfetch
    gimp
    ghostty
    gnome-calculator
    gnome-calendar
    gnome-extension-manager
    gnome-terminal
    gnome-tweaks
    #godot
    #hakuneko
    kdePackages.kdenlive
    keepassxc
    libreoffice-fresh
    librewolf
    #links2
    loupe
    mcrcon
    #mediawriter
    nautilus
    ncdu
    #osu-lazer-bin
    pcsx2
    #ppsspp
    #protonup
    prismlauncher
    qbittorrent
    rar
      unrar
    #remmina
    #sm64coopdx
    #spotdl
    tldr
    tor-browser
    #ventoy-full-gtk
    vesktop
    vim
    vlc
    #vscodium-fhs
    wget
    #winePackages.unstableFull
    wl-clipboard
    yt-dlp
    zip
      unzip
  ];
}
